[build]
  base = "."
  command = "npm run build"
  publish = "client/build"
  functions = "netlify/functions"

[build.environment]
  REACT_APP_API_URL = "/.netlify/functions"
  NODE_VERSION = "18"
  RSS_FEED_URL = "https://feeds.libsyn.com/84842/rss"

[dev]
  command = "npm run dev:client"
  port = 3000
  publish = "client/build"
  functions = "netlify/functions"
  framework = "create-react-app"

[dev.environment]
  REACT_APP_API_URL = "/.netlify/functions"
  RSS_FEED_URL = "https://feeds.libsyn.com/84842/rss"

# Redirect API calls to functions
[[redirects]]
  from = "/api/rss/episodes"
  to = "/.netlify/functions/episodes"
  status = 200

[[redirects]]
  from = "/api/rss/podcast-info"  
  to = "/.netlify/functions/podcast-info"
  status = 200

# Catch-all redirect for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Cache settings for functions
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Cache-Control = "public, max-age=300, s-maxage=600"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Accept"
    Access-Control-Allow-Methods = "GET, OPTIONS"

# Security headers for static files
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    X-XSS-Protection = "1; mode=block"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"